#!/bin/sh
# Copyright (C) 2014 Julien Bonjean <julien@bonjean.info>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

TYPE="${BLOCK_INSTANCE:-mem}"

awk -v type=$TYPE '
/^MemTotal:/ {
	mem_total=$2
}
/^MemFree:/ {
	mem_free=$2
}
/^Buffers:/ {
	mem_free+=$2
}
/^Cached:/ {
	mem_free+=$2
}
/^SwapTotal:/ {
	swap_total=$2
}
/^SwapFree:/ {
	swap_free=$2
}
/^MemAvailable:/ {
    mem_available=$2
}
END {
	# full text, short_text, color
	if (type == "swap") {
		printf("%.1fG\n", (swap_total-swap_free)/1024/1024)
		printf("%.1fG\n", (swap_total-swap_free)/1024/1024)
                if (swap_free/swap_total < 0.1) {
                    printf "#ff0000\n"
	    	} else if (swap_free/swap_total < 0.2) {
                    printf "#FFAE00\n"
	    	} else if (swap_free/swap_total < 0.4) {
                    printf "#FFF600\n"
    		}
        } else {
		printf("%.1fG\n", mem_free/1024/1024)
		printf("%.1fG\n", mem_free/1024/1024)
                if (mem_available/mem_total < 0.1) {
                    printf "#FF0000\n"
                } else if (mem_available/mem_total < 0.2) {
                    printf "#FFAE00\n"
                } else if (mem_available/mem_total < 0.4) {
                    printf "#FFF600\n"
                }
        }
}
' /proc/meminfo
