#!/bin/bash

menu() {
	echo
	echo "---"
	echo "1 - ncmpcpp"
	echo "2 - alsamixer"
	echo "3 - b+"
	echo "4 - b-"
	echo "9 - screenlock"
	echo "0 - exit"
}

C=-1

while [[ "$C" != "0" ]]; do
  menu
  read -t 5 -n 1 -p "Choice> " C
  case $C in
	  1) ncmpcpp
		  ;;
	  2) alsamixer
		  ;;
	  3) b+
		  ;;
	  4) b-
		  ;;
	  9) exec screenlock
		  ;;
	  0) echo; exit
		  ;;
	  "") echo; exit
		  ;;
  esac
done
