#!/bin/bash
EXTERNAL_OUTPUT="HDMI1"
INTERNAL_OUTPUT="eDP1"
# if we have argument on command line - execute
if [[ $# -eq 1 ]]; then
	if [[ "$1" == "extend" ]]; then
		xrandr --output $INTERNAL_OUTPUT --auto --output $EXTERNAL_OUTPUT --auto --right-of $INTERNAL_OUTPUT
	elif [[ "$1" == "single" ]]; then
        	xrandr --output $INTERNAL_OUTPUT --auto --output $EXTERNAL_OUTPUT --off
	elif [[ "$1" == "same" ]]; then
		xrandr --output $INTERNAL_OUTPUT --auto --output $EXTERNAL_OUTPUT --auto --same-as $INTERNAL_OUTPUT
	fi
	exit 0
fi


# if we don't have a file, start at zero
if [ ! -f "/tmp/monitor_mode.dat" ] ; then
  monitor_mode="INTERNAL"

# otherwise read the value from the file
else
  monitor_mode=`cat /tmp/monitor_mode.dat`
fi

# toggle between extended and internal only
if [ $monitor_mode = "EXTEND" ]; then
        monitor_mode="INTERNAL"
        xrandr --output $INTERNAL_OUTPUT --auto --output $EXTERNAL_OUTPUT --off
elif [ $monitor_mode = "INTERNAL" ]; then
        monitor_mode="EXTEND"
	xrandr --output $INTERNAL_OUTPUT --auto --output $EXTERNAL_OUTPUT --auto --right-of $INTERNAL_OUTPUT
fi

notify-send Monitor\ mode "${monitor_mode}\ $(xrandr | egrep -v "^ " | cut -d \  -f1,2)"

# finally store the current mode
echo "${monitor_mode}" > /tmp/monitor_mode.dat

